### ISSUE TITLE
Profile verification

### ISSUE THREAD

**Issue by amenes12** [lospentiumsupc/waw-frontend-vue#3]
## Feature request

- [X] **I have looked at all the other requests before I submitted this issue**

### Summary

Create a button in the profile view where users cand send their own profile to verification

### Suggested solution(s)

Add a button 'Verify' in the profile section with [PrimeVue Buttons](https://www.primefaces.org/primevue/button), it'll be great if you use the **help** severity. When a user presses the button, it appears a [PrimeVue ConfirmDialog](https://www.primefaces.org/primevue/confirmdialog) to confirm (obviously) or deny the action. Finally, if the user confirmed or denied the verification, there is a [PrimeVue Toast](https://www.primefaces.org/primevue/toast) according to what the action was (success severity if the user confirmed or error severity if the user denied).

**Comment by dalbitresb12** [comment]
Fixed by #6.
