### ISSUE TITLE
Employees recomendation

### ISSUE THREAD

**Issue by amenes12** [lospentiumsupc/waw-frontend-vue#5]
## Feature request

- [x] **I have looked at all the other requests before I submitted this issue**

### Summary

Employers may want to rate employees' profiles, so that they can be recommended users and get more job offers 

### Suggested solution(s)

Use [PrimeVue Rating](https://www.primefaces.org/primevue/rating) component to implement this feature

**Comment by dalbitresb12** [comment]
Fixed by #14.
